name: graph-learn CD

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        python-version: [3.6, 3.7, 3.8, 3.9]
        include:
          - { os: ubuntu-18.04, python-version: 3.6, python-abis: "cp36-cp36m" }
          - { os: ubuntu-18.04, python-version: 3.7, python-abis: "cp37-cp37m" }
          - { os: ubuntu-18.04, python-version: 3.8, python-abis: "cp38-cp38" }
          - { os: ubuntu-18.04, python-version: 3.9, python-abis: "cp39-cp39" }

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy python packages
        if: startsWith(github.ref, 'refs/tags/') && matrix.no-deploy != '1'
        shell: bash
        env:
          DOCKER_IMAGE: "quay.io/pypa/manylinux_2_24_x86_64"
          PYABI: ${{ matrix.python-abis }}
          PYPI_PWD: ${{ secrets.PYPI_PWD }}
        run: |
          source ./.github/workflows/upload_packages.sh