name: graph-learn CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04, macos-latest]
        python-version: [2.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
        python-abis: "cp27-cp27mu"
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 graphlearn --count --select=E9,F63,F7,F82 --ignore=E111 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 graphlearn --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Make test
      run: make test
    - name: Test env
      run: source env.sh
    - name: Cpp test
      run: ./test_cpp_ut.sh
    - name: Python package&test in docker.
      shell: bash
      run: |
        sudo docker run --rm --name tf112 --net=host -v $(pwd):/gl tensorflow/tensorflow:1.12.0 bash -c '
        apt-get update
        apt-get -y install git
        python -m pip install --upgrade pip setuptools wheel
        # install ssl
        apt-get -y install wget
        wget https://www.openssl.org/source/openssl-1.1.1f.tar.gz
        tar -xzvf openssl-1.1.1f.tar.gz
        cd openssl-1.1.1f
        ./config shared zlib-dynamic
        make -j 32
        mkdir -p /usr/lib64
        cp libcrypto.so.1.1 /usr/lib64/
        cp libssl.so.1.1 /usr/lib64/
        cd /usr/lib64
        ln -s libssl.so.1.1 libssl.so
        ln -s libcrypto.so.1.1 libcrypto.so
        # make&install wheel
        cd /gl
        make python
        pip install dist/*.whl
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64:/usr/local/lib/python2.7/dist-packages/graphlearn/python/lib
        # test python
        ./test_python_ut.sh
        '
